services:
  # Backend Service
  - type: web
    name: comments-app-backend
    env: docker
    docker:
      dockerfile: ./backend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
    plan: free
    numInstances: 1

  # Frontend Service  
  - type: web
    name: comments-app-frontend
    env: docker
    docker:
      dockerfile: ./frontend/Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: comments-app-backend
          type: web
          property: host
    plan: free
    numInstances: 1